global:

cost-analyzer:
  persistentVolume:
    enabled: false

  networkPolicy:
    enabled: true

  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "2048Mi"

  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  nodeSelector: {}
  tolerations: []
  affinity: {}

  prometheus:
    enabled: false
  grafana:
    enabled: false

  serviceAccount:
    create: true
    name: kubecost-service-account
  rbac:
    create: true
